services:
  postgres:
    image: postgres:16
    container_name: pedidos_postgres
    environment:
      POSTGRES_DB: pedidos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pedidos_postgres_data:/var/lib/postgresql/data
      - ./backend/migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql

volumes:
  pedidos_postgres_data:
