// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXQye3zd9Ono8dshyuzGspTdg-KEM3l6M',
    appId: '1:870215874691:web:9e2878a42170bfc45983b6',
    messagingSenderId: '870215874691',
    projectId: 'pedidos-mobile-jorge',
    authDomain: 'pedidos-mobile-jorge.firebaseapp.com',
    storageBucket: 'pedidos-mobile-jorge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi4f1n6CU2nL0z3ArN8gHiievGx7TZo-Y',
    appId: '1:870215874691:android:a0c387eeca995ebb5983b6',
    messagingSenderId: '870215874691',
    projectId: 'pedidos-mobile-jorge',
    storageBucket: 'pedidos-mobile-jorge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo-AImsplFPNISP7WD9RI2U7Z4GTl6-II',
    appId: '1:870215874691:ios:afc8f82fe856220b5983b6',
    messagingSenderId: '870215874691',
    projectId: 'pedidos-mobile-jorge',
    storageBucket: 'pedidos-mobile-jorge.firebasestorage.app',
    iosBundleId: 'com.ssjorge.pedidosMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo-AImsplFPNISP7WD9RI2U7Z4GTl6-II',
    appId: '1:870215874691:ios:afc8f82fe856220b5983b6',
    messagingSenderId: '870215874691',
    projectId: 'pedidos-mobile-jorge',
    storageBucket: 'pedidos-mobile-jorge.firebasestorage.app',
    iosBundleId: 'com.ssjorge.pedidosMobile',
  );
}
